#!/bin/sh -e

case "$1" in
	configure)
		update-rc.d -f firewally remove >/dev/null 2>&1
		update-rc.d firewally defaults 15 85 >/dev/null
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;
esac
